# Generated by Django 5.0.4 on 2024-04-06 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
            ],
            options={
                'verbose_name': '게시글',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='post.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '게시글 구독자',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SubscriberFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='post.subscriber', verbose_name='구독자')),
            ],
            options={
                'verbose_name': '구독자 팔로워',
                'ordering': ['-id'],
            },
        ),
    ]
