# Generated by Django 5.0.4 on 2024-04-08 14:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0002_post_created_at_post_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('ticket_serial', models.CharField(max_length=12, verbose_name='티켓 시리얼 번호')),
                ('is_expired', models.BooleanField(default=True, verbose_name='만료여부')),
            ],
            options={
                'verbose_name': '티켓',
                'verbose_name_plural': '티켓 목록',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TicketSerialGenerator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('ticket_serial', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='티켓 시리얼 번호')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': '티켓 번호 생성기',
                'verbose_name_plural': '티켓 번호 생성기 목록',
                'indexes': [models.Index(fields=['uuid'], name='ticket_tick_uuid_40badb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ticketserialgenerator',
            constraint=models.UniqueConstraint(fields=('uuid',), name='unique_uuid'),
        ),
        migrations.AddField(
            model_name='userticket',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tickets', to='post.post', verbose_name='게시글'),
        ),
        migrations.AddField(
            model_name='userticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
        migrations.AddConstraint(
            model_name='userticket',
            constraint=models.UniqueConstraint(fields=('ticket_serial',), name='unique_post_user'),
        ),
    ]
